version: '3.8'

services:
  ctf-app:
    build: .
    container_name: sqli-time-based-ctf
    ports:
      - "8091:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      # Монтируем директорию для базы данных (опционально)
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.ctf.challenge=blind-sql-injection"
      - "com.ctf.difficulty=medium"
      - "com.ctf.category=web"
      - "com.ctf.description=Time-based Blind SQL Injection Challenge"
