name: Upload to web

on:
  workflow_run:
    workflows: ["check-tasks"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  upload-tasks:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pyyaml requests

      - name: Upload
        run: python3 .github/scripts/upload.py --url https://ctf.itsover.ru --api-key ${{ secrets.WEB_API_KEY }}
